#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

PORT="${PORT:-8000}"
RUNS_ROOT="${RUNS_ROOT:-/beegfs/jung/mmdet3d_legacy/projects/adv_aug/runs}"
VIS_DIR="${VIS_DIR:-}"
SSH_HOST="${SSH_HOST:-$(whoami)@$(hostname -f 2>/dev/null || hostname)}"

usage() {
  cat <<EOF
Usage:
  $0

Environment overrides:
  PORT       Port used by the HTTP server. Default: ${PORT}
  VIS_DIR    Directory served by HTTP server. Default: newest directory containing an HTML file under RUNS_ROOT
  RUNS_ROOT  Search root used when VIS_DIR is unset. Default: ${RUNS_ROOT}
  SSH_HOST   SSH target printed for regular terminal port forwarding. Default: ${SSH_HOST}

Run this on the remote machine, then use either VS Code's port forwarding for PORT
or a regular SSH tunnel from your local machine.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" || "${1:-}" == "help" ]]; then
  usage
  exit 0
fi

if [[ $# -gt 0 ]]; then
  echo "Unexpected argument: $1" >&2
  usage >&2
  exit 2
fi

if [[ -z "${VIS_DIR}" ]]; then
  VIS_DIR="$(
    find "${RUNS_ROOT}" -type f -name '*.html' -printf '%T@ %h\n' 2>/dev/null \
      | sort -nr \
      | head -n 1 \
      | cut -d' ' -f2-
  )"
fi

if [[ -z "${VIS_DIR}" ]]; then
  echo "No visualization HTML files found under: ${RUNS_ROOT}" >&2
  echo "Set VIS_DIR=/path/to/html/files to serve a specific directory." >&2
  exit 1
fi

if [[ ! -d "${VIS_DIR}" ]]; then
  echo "Visualization directory does not exist: ${VIS_DIR}" >&2
  exit 1
fi

mapfile -t HTML_FILES < <(
  find "${VIS_DIR}" -maxdepth 1 -type f -name '*.html' ! -name 'index.html' -printf '%f\n' | sort
)

if [[ "${#HTML_FILES[@]}" -eq 0 ]]; then
  echo "No HTML files found in visualization directory: ${VIS_DIR}" >&2
  exit 1
fi

INDEX_PATH="${VIS_DIR}/index.html"
if [[ ! -e "${INDEX_PATH}" ]] || grep -q 'generated by start_visualization_port_forward.sh' "${INDEX_PATH}"; then
  {
    cat <<EOF
<!doctype html>
<!-- generated by start_visualization_port_forward.sh -->
<html>
<head>
  <meta charset="utf-8">
  <title>Visualization Index</title>
</head>
<body>
  <h1>Visualization Index</h1>
  <p>Serving: ${VIS_DIR}</p>
  <ul>
EOF
    for html_file in "${HTML_FILES[@]}"; do
      printf '    <li><a href="%s">%s</a></li>\n' "${html_file}" "${html_file}"
    done
    cat <<EOF
  </ul>
</body>
</html>
EOF
  } > "${INDEX_PATH}"
else
  echo "Keeping existing index.html because it was not generated by this script."
fi

cat <<EOF
Serving visualizations from:
  ${VIS_DIR}

Found ${#HTML_FILES[@]} HTML file(s). First entries:
$(printf '  %s\n' "${HTML_FILES[@]:0:10}")

Starting:
  cd "${VIS_DIR}"
  python3 -m http.server ${PORT}

Forward port ${PORT} in VS Code, then open the forwarded local URL.

For a regular SSH terminal, start the server here and run this from your local machine:
  ssh -N -L ${PORT}:127.0.0.1:${PORT} ${SSH_HOST}

Then open:
  http://127.0.0.1:${PORT}/

Press Ctrl-C here to stop the HTTP server.
EOF
cd "${VIS_DIR}"
exec python3 -m http.server "${PORT}"
